env:
  global:
    - CC_TEST_REPORTER_ID=618e64226e212a5824797037cb1a71487cdbfb3aa664bddc42a7189fb027f73a
sudo: false
language: ruby
rvm:
  - 2.5.0
before_install: gem install bundler -v 1.16.1
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
